### ISSUE TITLE
Permissions and branch protecting

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/branding#3]
Hello everyone! :wave:  
I'm writing to you all here today to clarify a few things regarding the permission changes I made this Friday as well as a few other things.  

## Analytics and management of the site  
We receive between 100,000 to 200,000 requests on a normal day.  
If the site goes down for an hour that means around 6250 requests return a blank page or a CloudFlare error message.  

![requests twofactorauth](https://cloud.githubusercontent.com/assets/3535780/23170978/732402e8-f851-11e6-89f9-567942aa200d.png)

That is 6250 wasted requests and potentially ~6250 users that won't come back.  
That's not acceptable and because of that I and Josh have very carefully reviewed all commits before merging `master` with `gh-pages` which stores the live page.  

The reviewing is there to catch any merged PRs that broke the build without any errors from Travis-CI.  
This has happened a few times resulting in images not being displayed or the page not loading all categories.  

Back in June of 2015 Josh gave me permission (or "promoted" me as he put it) to do the merge process and to review, which I very carefully have done since.  
In the beginning I was so scared of breaking the `gh-pages` branch that I deleted the twofactorauth git folder on my local computer every time before merging, just to be sure that no un-reviewed commits had slipped through. :wink:  

To stop having to go through those extra steps just to verify the integrity of the local git history, I protected the branch back in 2016 when that feature was released. This helped my anxiety a lot as I knew that commits not already pushed to master got rejected if I happened to work with the wrong branch.  

I then set up a second security precaution to help everyone else here in case they happened to push to the wrong repository or branch. I locked the `gh-pages` branch down so that only I, Josh, Jacob and Mxxcon could push to the branch.  
This didn't work however, because the "owner" permission group (and "admin" group as I later found out) have an exception to the lock-down.  
This decision was to me a no-brainier as I didn't see any reason for people to have those extra permissions which granted them to add people to the group or make new repositories for 2factorauth.  

My decision was however met with a not so happy reaction from the people I removed from the group. There are a few cases when they do need owner permissions for their regular work which I didn't anticipate when looking at the pros and cons.  
Some of you also viewed it as me trying to limit your abilities and make this community centrally controlled by me and Josh and limiting everyone else's say. That was not my intention at all and I'm very sorry if you interpreted it that way.  
The only reason I removed the owner group permissions was to eliminate the fear one might have of accidentally pushing things to the live site.  

The clear majority do however disagree with my action which is why I today reverted it back to normal. Everyone that was in the "owner" permission group earlier is now back in the group.  

I'd like to thank everyone raising their concerns. Together we make this organization better! :smile:  

![review process](https://cloud.githubusercontent.com/assets/3535780/23171117/e7bb217c-f851-11e6-9d27-42375fa0a148.png)

## Future
So limiting the permissions was clearly a bad idea but I still think that protecting the `gh-pages`branch is.  
Maybe instead of giving a few people permission to review a merge we should allow everyone to do so?  
In that case I think some sort of bot would be the best option.  
When a review was started and enough people signed off on it then the bot would merge.  
What are your thoughts on this? Do you have any other ideas on how to simplify this process? Post a comment!  

Thank you for your time!  
//@Carlgo11

**Comment by jamcat22** [comment]
I do agree that more granular permissions should be used, and it's a shame GitHub doesn't allow a better system for setting permissions on repos and protected branches.

I'd almost consider having the `gh-pages` branch require PR reviews before merging (including for administrators), and have a system where we make a PR before merging, then have multiple contributors test locally and review before merging.

**Comment by mxxcon** [comment]
@Carlgo11 I think there's one large misinterpretation in those stats. 
Requests != page views. Requests = all resources on a page. Considering we have a huge number of logo images, it skews this stat. A more accurate stat would be "Unique Visitors".
If the site goes down, doesn't CloudFlare have "Always Online" option?
Also we should consider settings our browser cache timeout to more than just 4 hours. Our content doesn't change often enough to warrant such short ttl. I think at least 1 day is more sensible.

**Comment by psgs** [comment]
In terms of permissions for members of the `2factorauth` organisation, I think it's necessary we try to find a balance between the following situations:

* Less permissions are better (Most members having permissions they don't use is a security risk)
* Access to permissions such as API access and repository creation allows members to branch out on their own and innovate
* Timely/redundant access (In some cases, Carl and Josh may not be available when changes to `gh-pages`, Cloudflare and the organisation are necessary in order to maintain the functioning of the website)

A bot for `gh-pages` that would make changes based on a number of votes sounds like a great idea. We could create it for use with Slack and program it so it's able to be used by other organisations, turning it into its' own project.

**Comment by stephengroat** [comment]
Also, figuring out a way to add more APIs in the review process would be good.

there's no good reason for us to check `facebook` and `twitter` manually anymore :man_factory_worker:

**Comment by mxxcon** [comment]
How would you automate that this Twitter/Facebook belongs to this company?

**Comment by stephengroat** [comment]
for example, looking at the url associated with the twitter/facebook
profile (and it's verification status for twitter)
